# Generated by Django 2.2.16 on 2023-02-06 18:20

from django.db import migrations
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221102_0939'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=posts.models.Base64ImageField(blank=True, null=True, upload_to='posts/images/'),
        ),
    ]
